version: "3.9"

services:

  nginx:
    image: "nginx:latest"
    ports: 
      - "8080:80"
      - "443:443"    
    links:
      - php
    volumes: 
      - ./www:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    networks:
      - net

  php:
    image: "php:fpm"
    volumes:
      - ./www:/var/www/html
      - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    links:
      - redis
    networks:
      - net

  redis:
    image: "redis"
    networks:
      - net
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.241.2.0/24      
